### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Failed to send GC message: Timeout

### ISSUE THREAD

**Issue by koutsie** [BeepIsla/fake-stattrak#2]
```(node:26809) UnhandledPromiseRejectionWarning: Error: Failed to send GC message: Timeout
    at Timeout._onTimeout (/home/koutsie/Downloads/fake-stattrak-master/helpers/Coordinator.js:92:12)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(node:26809) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:26809) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by BeepIsla** [comment]
This is not enough information.

**Comment by koutsie** [comment]
![image](https://user-images.githubusercontent.com/18449778/76783880-591f7300-67bb-11ea-9b90-dbd6aaf19de9.png)
literally only thing im getting tho?

**Comment by BeepIsla** [comment]
You did not send the first line saying `UnhandledPromiseRejectionWarning: Error: failed to send GC message: Timeout` which was the important part.

Is this the first `Fake joining server...` log or the second one? It should show it twice, once for the bot account, once for the main account.

**Comment by koutsie** [comment]
```js
[koutsie@koutsie-pc fake-stattrak-master]$ node index.js 
Validating protobufs...
Found protobufs!
Requiring files for appID 730
Creating constructors...
Logging into Steam as client and server...
Steam Guard App Code: [CODE]
Successfully logged into Steam and signed up as bot account as [KOUTSIE_BOT]
Successfully logged into Steam and signed up as main account as [KOUTSIE]
Successfully logged into Steam and signed up as server as [unrelated_id]
Fake joining server with bot account [KOUTSIE_BOT]
Successfully added player to server, verifying on client...
(node:27434) UnhandledPromiseRejectionWarning: Error: Failed to send GC message: Timeout
    at Timeout._onTimeout (/home/koutsie/Downloads/fake-stattrak-master/helpers/Coordinator.js:92:12)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(node:27434) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:27434) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by BeepIsla** [comment]
Okay this is a lot more information to work with, thanks.

---

The problem seems to be that the bot account tries to tell CSGO it is joining the server. CSGO does not respond to this and I have no idea why.

I will try to see if it works for me and if I can maybe find a work around to make StatTrak boosting work without this request.

**Comment by koutsie** [comment]
**Awesome**, thanks and good luck!

**Comment by BeepIsla** [comment]
It worked perfectly fine for me without any issues. A quick test showed it continued to work after removing the message the account tries to send to CSGO.

Luckily the data CSGO responds with isn't required so I simply removed the response, it still sends it out but ignores failure and the response. (e3c921e2c686288ef195a5cc88479b7fead9735e)

If you continue to have issues its possible that this is a problem with the account itself and not the script. Give it a try.

**Comment by koutsie** [comment]
Works now, thanks!
