### ISSUE TITLE
ReferenceError: fetch is not defined. anyone help?

### ISSUE THREAD

**Issue by wk2poor** [BeepIsla/fake-stattrak#28]
at Function.downloadProtobufs (C:\Users\q\Downloads\fake-stattrak-master\fake-stattrak-master\helpers\Helper.js:39:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\q\Downloads\fake-stattrak-master\fake-stattrak-master\index.js:37:3
Failed to download protobufs.

**Comment by BeepIsla** [comment]
You are running an outdated version of NodeJS, update here: https://nodejs.org/en/

`fetch` was added in version 18.

**Comment by wk2poor** [comment]
thanks! your a awesome developer
