### ISSUE TITLE
Trouble Using This in November of 2023

### ISSUE THREAD

**Issue by femboyrust** [BeepIsla/fake-stattrak#39]
I'm trying to use this but finding myself unable to do so, I'm getting login errors but I believe thats only because I have steam guard and I do not see a place in which to put a code for either account. Is there any chance of this working? My goal is to get to the strange limit of 2.49 billion. No worries if you dont want to come back to this problem after so long. Slight bummer but I'd understand.

**Comment by BeepIsla** [comment]
When you log into an account with Steam Guard it should ask you for the code in the same window. Its possible this is now broken due to Steam having changed the way logins work a while ago. Can you try running `npm update` and then `node index.js` and see if that solves the issue for now?

**Comment by femboyrust** [comment]
Upon running the npm update I received 
"added 17 packages, removed 199 packages, changed 16 packages, and audited 90 packages in 4s"
After running "node index.js" I was met with:
"Error: InvalidPassword
           at Steamuser._handleLogOnResponse (C:\Users\123|Desktop\fake-stattrak-master\node_modules\steam-user\componets\0-9logon.js:775:17)
           at C:\Users\123\Desktop\fake-stattrak-master\node_modules\steam-user\componets\o9-logon.js:400:10 {
        eresult: 5
}       

I did not receive any prompt to enter a steam code.

**Comment by BeepIsla** [comment]
In my test it appears that I can login fine after upgrading all dependencies but my strange weapon doesn't appear to gain any kills. Not sure why and I am not really gonna bother looking into it.

**Comment by femboyrust** [comment]
That's fine, thanks for responding at all :)
