### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Wieselnuggis123** [BeepIsla/fake-stattrak#41]
Hey so we tested it multiple times and it does not work anymore but we dont know why. Maybe u can help

**Comment by BeepIsla** [comment]
Which game?

**Comment by Wieselnuggis123** [comment]
> Which game?

tf2

**Comment by Wieselnuggis123** [comment]
we started after it got 300000 kills it said finsish but nohing changed

**Comment by BeepIsla** [comment]
There have been some issues with TF2 for a while and I am not sure why.

**Comment by Wieselnuggis123** [comment]
> There have been some issues with TF2 for a while and I am not sure why.

it does not print any issues in the console besides this: (node:22464) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use node --trace-warnings ... to show where the warning was created)

**Comment by BeepIsla** [comment]
That warning can be safely ignored. The issue is somewhere with what we send to the TF2 backend, it seems to ignore it for some reason and I don't know why.

**Comment by Wieselnuggis123** [comment]
but do you know where exactly the issue is like in what code

**Comment by BeepIsla** [comment]
Somewhere in here https://github.com/BeepIsla/fake-stattrak/blob/878922012dcd1ef4e3ee858ebf35cea7a39af902/components/Server_440.js#L82-L121

**Comment by oxyGodmode** [comment]
its be nice to fix this script :)

**Comment by BeepIsla** [comment]
You can try simply changing the `1_000` number in there to a lower number and running the script again. Maybe that fixes it? I have no time right now to test aronud.

**Comment by Wieselnuggis123** [comment]
> You can try simply changing the `1_000` number in there to a lower number and running the script again. Maybe that fixes it? I have no time right now to test aronud.

like 0.9_000

**Comment by BeepIsla** [comment]
Remove the underscore `1_000` -> `1000` and make it any number you want. Maybe it works with `100` or `500`, I don't know.

**Comment by Wieselnuggis123** [comment]
ill try

**Comment by Wieselnuggis123** [comment]
i ran before i made the change and it gave me this errror: C:\Users\Wieselnuggis\Downloads\fake-stattrak-master\fake-stattrak-master\components\Client_Shared.js:116
                                                reject(new Error("Failed to connect to Steam"));
                                                       ^

Error: Failed to connect to Steam
    at C:\Users\Wieselnuggis\Downloads\fake-stattrak-master\fake-stattrak-master\components\Client_Shared.js:116:14

Node.js v21.6.1

**Comment by BeepIsla** [comment]
In TF2? That shouldn't happen.

**Comment by Wieselnuggis123** [comment]
nvm i fucked smth up trying rn with the change

**Comment by oxyGodmode** [comment]
wiesel biber

**Comment by Wieselnuggis123** [comment]
still does not work
even after u changed the number to 100

**Comment by Wieselnuggis123** [comment]
trying 500 now

**Comment by BeepIsla** [comment]
If a lower number does not work then a higher number probably won't either

**Comment by Wieselnuggis123** [comment]
so chagne the number in front to my likings or the behind the :

**Comment by BeepIsla** [comment]
change both `1_000` to the same number

**Comment by Wieselnuggis123** [comment]
i have these rn 		let maximumMultipleChildren = 1_000;
		let increment = eventTypeInfo?.allowIncrement ? 1000 : 100;

**Comment by Wieselnuggis123** [comment]
so change the top to 100 the bottom to 100 and the 100 aftzer the : back to 1?

**Comment by BeepIsla** [comment]
Don't change the 1. Only change the two 1000s

**Comment by Wieselnuggis123** [comment]
alr

**Comment by Wieselnuggis123** [comment]
that happend
C:\Users\Wieselnuggis\Downloads\fake-stattrak-master\fake-stattrak-master\node_modules\steam-user\components\09-logon.js:809
                                let error = new Error(EResult[body.eresult] || body.eresult);
                                            ^

Error: RateLimitExceeded
    at SteamUser._handleLogOnResponse (C:\Users\Wieselnuggis\Downloads\fake-stattrak-master\fake-stattrak-master\node_modules\steam-user\components\09-logon.js:809:17)
    at C:\Users\Wieselnuggis\Downloads\fake-stattrak-master\fake-stattrak-master\node_modules\steam-user\components\09-logon.js:441:16 {
  eresult: 84
}

Node.js v21.6.1

**Comment by BeepIsla** [comment]
You logged in too many times, you are now prevented from logging in for 30 minutes. If you try to login again before this time expires it will reset.

**Comment by Wieselnuggis123** [comment]
so i have to wait

**Comment by Wieselnuggis123** [comment]
alr

**Comment by Wieselnuggis123** [comment]
still does not work but imma go to sleep maybe there are other ways to fix

**Comment by Wieselnuggis123** [comment]
nvm 500 on both works

**Comment by Wieselnuggis123** [comment]
thats the fix

**Comment by Wieselnuggis123** [comment]
but there is still 1 problem in console there is 3mil kills but only 200k or so got added to strange part

**Comment by Wieselnuggis123** [comment]
maybe u can give me your dc i have some other questions that i dont want to be public

**Comment by BeepIsla** [comment]
My Discord name is the as on Github
